// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsundokuTraducoes.Api.Data;

#nullable disable

namespace TsundokuTraducoes.Api.Migrations
{
    [DbContext(typeof(TsundokuContext))]
    [Migration("20230529015739_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TsundokuTraducoes.Api.Models.CapituloManga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConteudoManga")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescritivoCapitulo")
                        .HasColumnType("longtext");

                    b.Property<string>("DiretorioCapitulo")
                        .HasColumnType("longtext");

                    b.Property<double>("Numero")
                        .HasColumnType("double");

                    b.Property<int>("OrdemCapitulo")
                        .HasColumnType("int");

                    b.Property<string>("Parte")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext");

                    b.Property<int>("VolumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CapitulosManga");
                });

            modelBuilder.Entity("TsundokuTraducoes.Api.Models.GeneroObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int?>("ObraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GenerosObra");
                });

            modelBuilder.Entity("TsundokuTraducoes.Models.CapituloNovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConteudoNovel")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescritivoCapitulo")
                        .HasColumnType("longtext");

                    b.Property<string>("DiretorioCapitulo")
                        .HasColumnType("longtext");

                    b.Property<bool>("EhIlustracoesNovel")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Numero")
                        .HasColumnType("double");

                    b.Property<int>("OrdemCapitulo")
                        .HasColumnType("int");

                    b.Property<string>("Parte")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext");

                    b.Property<int>("VolumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CapitulosNovel");
                });

            modelBuilder.Entity("TsundokuTraducoes.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Ação",
                            Slug = "acao"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Aventura",
                            Slug = "aventura"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Comédia",
                            Slug = "comedia"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Drama",
                            Slug = "drama"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Slice of Life",
                            Slug = "slice-of-life"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Isekai",
                            Slug = "isekai"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Harém",
                            Slug = "harem"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Horror",
                            Slug = "horror"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Fantasia",
                            Slug = "fantasia"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Seinen",
                            Slug = "seinen"
                        });
                });

            modelBuilder.Entity("TsundokuTraducoes.Models.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .HasColumnType("longtext");

                    b.Property<string>("Ano")
                        .HasColumnType("longtext");

                    b.Property<string>("Artista")
                        .HasColumnType("longtext");

                    b.Property<string>("AutorObra")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoCorHexaIndice")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAtualizacaoUltimoCapitulo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiretorioObra")
                        .HasColumnType("longtext");

                    b.Property<bool>("EhObraMaiorIdade")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EnderecoUrlCapa")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUltimoVolume")
                        .HasColumnType("longtext");

                    b.Property<string>("NacionalidadeSlug")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroUltimoCapitulo")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroUltimoVolume")
                        .HasColumnType("longtext");

                    b.Property<string>("Sinopse")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("SlugUltimoCapitulo")
                        .HasColumnType("longtext");

                    b.Property<string>("SlugUltimoVolume")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusObraSlug")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoObraSlug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<string>("TituloAlternativo")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext");

                    b.Property<int>("Visualizacoes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("TsundokuTraducoes.Models.Volume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescritivoVolume")
                        .HasColumnType("longtext");

                    b.Property<string>("DiretorioVolume")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemVolume")
                        .HasColumnType("longtext");

                    b.Property<double>("Numero")
                        .HasColumnType("double");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Sinopse")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Volumes");
                });
#pragma warning restore 612, 618
        }
    }
}
